language: objective-c
osx_image: xcode7.3

xcode_project: weTranslate.xcodeproj
xcode_scheme: weTranslate
xcode_sdk: iphonesimulator9.3

notifications:
  slack: wetranslateteam:FaCCuM3G8pNFJzfCsGOLcvBy#ios-annonce
