language: objective-c
osx_image: xcode7.3
script: set -o pipefail && xcodebuild test -project weTranslate.xcodeproj -scheme weTranslate -sdk iphonesimulator9.3 | xcpretty

notifications:
  slack: wetranslateteam:FaCCuM3G8pNFJzfCsGOLcvBy#ios-annonce
