language: objective-c
osx_image: xcode8.2
script: set -o pipefail && xcodebuild test -project weTranslate.xcodeproj -scheme weTranslate -sdk iphonesimulator10.2 | xcpretty

notifications:
  slack: wetranslateteam:FaCCuM3G8pNFJzfCsGOLcvBy#ios-annonce
