language: objective-c
osx_image: xcode7.1

before_install:
  - brew update
  - brew upgrade xctool
  - brew install carthage
  - carthage bootstrap --platform iOS --verbose

xcode_project: weTranslate.xcodeproj
xcode_scheme: weTranslate
xcode_sdk: iphonesimulator9.1
